ALTER TABLE "scores" ADD "nmr0" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "nmr520" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "nmr208" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "nmr156" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "nmr104" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "nmr52" DOUBLE PRECISION NOT NULL DEFAULT '0';
