ALTER TABLE "runs" ADD "day" VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE "runs" ADD "session" VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE "runs" ADD "best_score" DOUBLE PRECISION NOT NULL DEFAULT '0';
