ALTER TABLE "scores" ADD "forward_week_returns" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "indicator_count" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "profit_target_over_stoploss" DOUBLE PRECISION NOT NULL DEFAULT '0';

ALTER TABLE "scores" ADD "trade_win_over_loss0" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_rate0" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_average0" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_count0" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "edge0" DOUBLE PRECISION NOT NULL DEFAULT '0';

ALTER TABLE "scores" ADD "min_sharpes520" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "tawal520" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_rate520" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_over_loss520" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_average520" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_count520" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "edge520" DOUBLE PRECISION NOT NULL DEFAULT '0';

ALTER TABLE "scores" ADD "min_sharpes208" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "tawal208" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_rate208" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_over_loss208" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_average208" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_count208" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "edge208" DOUBLE PRECISION NOT NULL DEFAULT '0';

ALTER TABLE "scores" ADD "min_sharpes156" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "tawal156" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_rate156" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_over_loss156" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_average156" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_count156" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "edge156" DOUBLE PRECISION NOT NULL DEFAULT '0';

ALTER TABLE "scores" ADD "min_sharpes104" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "tawal104" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_rate104" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_over_loss104" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_average104" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_count104" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "edge104" DOUBLE PRECISION NOT NULL DEFAULT '0';

ALTER TABLE "scores" ADD "tawal52" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_rate52" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_over_loss52" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_average52" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_count52" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "edge52" DOUBLE PRECISION NOT NULL DEFAULT '0';

ALTER TABLE "scores" ADD "min_sharpes26" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "tawal26" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_rate26" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_over_loss26" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_average26" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_count26" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "edge26" DOUBLE PRECISION NOT NULL DEFAULT '0';

ALTER TABLE "scores" ADD "min_sharpes13" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "tawal13" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_rate13" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_over_loss13" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_average13" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_count13" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "edge13" DOUBLE PRECISION NOT NULL DEFAULT '0';

ALTER TABLE "scores" ADD "min_sharpes8" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "tawal8" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_rate8" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_over_loss8" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_average8" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_count8" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "edge8" DOUBLE PRECISION NOT NULL DEFAULT '0';

ALTER TABLE "scores" ADD "min_sharpes4" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "tawal4" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_rate4" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_win_over_loss4" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_average4" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "trade_count4" DOUBLE PRECISION NOT NULL DEFAULT '0';
ALTER TABLE "scores" ADD "edge4" DOUBLE PRECISION NOT NULL DEFAULT '0';
